# escape=`

#FROM mcr.microsoft.com/windows/servercore/insider:10.0.20348.1 as buildbase
  
FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS buildbase

WORKDIR /tmp

SHELL [ "cmd", "/S", "/C" ]

ADD https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe Miniforge.exe
# RUN powershell (Get-FileHash .\mambaforge.exe).Hash -eq 'b33797064593ab2229a0135dc69001bea05cb56a20c2f243b1231213642e260a' && \
RUN start /wait "" Miniforge.exe /InstallationType=JustMe /RegisterPython=1 /S /D=C:\.build\Miniforge3
RUN C:\.build\Miniforge3\Library\bin\conda init && C:\.build\Miniforge3\Library\bin\conda clean -afy
RUN mamba install -n base -y anypytools pytest pytest-xdist pandas
RUN C:\.build\Miniforge3\Library\bin\conda clean -afy


ADD https://github.com/git-for-windows/git/releases/download/v2.33.0.windows.2/PortableGit-2.33.0.2-64-bit.7z.exe portableGit.7z.exe

ADD https://www.7-zip.org/a/7z1900-x64.exe 7zsetup.exe
RUN 7zsetup.exe /S /D="c:\.build\7zip"

RUN C:\.build\7zip\7z.exe x portableGit.7z.exe -oc:\.build\git
    

#works FROM mcr.microsoft.com/windows/servercore:ltsc2022
#FROM mcr.microsoft.com/windows/servercore/insider:10.0.20348.1

FROM mcr.microsoft.com/windows/servercore:ltsc2019



# default and makes hadolint skip this container
SHELL [ "cmd", "/S", "/C" ]

# Copy over AnyBody
COPY ["AnyBody.7.3-minimal/", "AnyBody.7.3-extra/", "dlls/",  "C:/Program Files/AnyBody Technology/AnyBody.7.3/"]
#COPY ["license.lic", "C:/Program Files/AnyBody Technology/AnyBody.7.3/"]


# Copy over git, 7zip and Miniforge
COPY --from=buildbase ["c:/.build/", "c:/"]

USER ContainerAdministrator

RUN C:\Miniforge3\Library\bin\conda init && C:\Miniforge3\Library\bin\conda clean -afy && `
    reg add HKCR\AnyBody.AnyScript\shell\Open\command1 /v "" /t REG_SZ /d "\"C:\Program Files\AnyBody Technology\AnyBody.7.3\AnyBody.exe\" \"%1\""  && `
    setx /M Path "C:\Miniforge3\condabin;C:\git\bin;C:\git\usr\bin;C:\git\mingw64\bin;%Path%;C:\7zip"


RUN setx /M Path "C:\Miniforge3\;C:\Miniforge3\Library\mingw-w64\bin;C:\Miniforge3\Library\usr\bin;C:\Miniforge3\Library\bin;C:\Miniforge3\Scripts;C:\Miniforge3\bin;%Path%"


ENV RLM_LICENSE=5053@104.46.46.229
ENV RLM_LICENSE_PASSWORD "1235"

RUN mkdir "%LOCALAPPDATA%\AnyBody Technology\AnyBody.7.3.x" && `
    mkdir "%APPDATA%\AnyBody Technology\AnyBody.7.3.x" && `
    mkdir "c:\ProgramData\AnyBody Technology\AnyBody.7.3.x"


# Test
# RUN conda list && conda create --name testenv numpy --dry-run && conda clean -afy


CMD ["cmd"]