#syntax=docker/dockerfile:1.4

ARG ANYBODY_VERSION 7.4
ARG ANYBODY_VERSION_PATCH 2
ARG ANYBODY_VERSION_SUFFIX ""
ARG BUILD_NUMBER 0

ARG BASE_IMAGE="ghcr.io/anybody/anybodycon-linux"
ARG TAG=${ANYBODY_VERSION}.${ANYBODY_VERSION_PATCH}${ANYBODY_VERSION_SUFFIX}-${BUILD_NUMBER}


FROM ${BASE_IMAGE}:${TAG}
ARG ANYBODY_VERSION
ARG ANYBODY_VERSION_SUFFIX

LABEL org.opencontainers.image.url https://github.com/AnyBody/anybody-container/pkgs/container/anybodycon-linux-minimal
LABEL org.opencontainers.image.title "anybodycon-linux-github-actions"
LABEL org.opencontainers.image.description "Image with AnyBody in a linux docker container for github actions"
LABEL org.opencontainers.image.licenses "https://www.anybodytech.com/legal/software-license-agreement/"


# Change the default uid:gid to be easily compatible with github actions
ARG NEW_MAMBA_USER=anybodyuser
ARG NEW_MAMBA_USER_ID=1001
ARG NEW_MAMBA_USER_GID=121

USER root
RUN usermod "--login=${NEW_MAMBA_USER}" "--home=/home/${NEW_MAMBA_USER}" \
        --move-home "-u 1001" "${MAMBA_USER}" && \
    groupmod "--new-name=${NEW_MAMBA_USER}" \
             "-g 121" "${MAMBA_USER}" && \
    # Update the expected value of MAMBA_USER for the
    # _entrypoint.sh consistency check.
    echo "${NEW_MAMBA_USER}" > "/etc/arg_mamba_user" && \
    :
ENV MAMBA_USER=$NEW_MAMBA_USER

# Change the GID/UID of wine to values which work with github actions
RUN chown 1001:121 /wine && \
 chown -R 1001:121 /wine/drive_c/users/$MAMBA_USER && \
 chown 1001:121 /wine/user.reg && \
 chown 1001:121 /wine/system.reg && \
 chown -R 1001:121 /home/$MAMBA_USER && \
 chown -R 1001:121 /opt/conda

ENV MAMBA_USER=$NEW_MAMBA_USER

USER ${NEW_MAMBA_USER}

