#syntax=docker/dockerfile:1.4

ARG ANYBODY_VERSION 7.4
ARG ANYBODY_VERSION_PATCH 2
ARG ANYBODY_VERSION_SUFFIX ""
ARG BUILD_NUMBER 0

ARG BASE_IMAGE="ghcr.io/anybody/anybodycon-linux-minimal"
ARG TAG=${ANYBODY_VERSION}.${ANYBODY_VERSION_PATCH}${ANYBODY_VERSION_SUFFIX}-${BUILD_NUMBER}

FROM ghcr.io/anybody/container-build-store:${ANYBODY_VERSION}.${ANYBODY_VERSION_PATCH}${ANYBODY_VERSION_SUFFIX} as anybody-build-store


FROM ${BASE_IMAGE}:${TAG}
ARG ANYBODY_VERSION
ARG ANYBODY_VERSION_SUFFIX

LABEL org.opencontainers.image.url https://github.com/AnyBody/anybody-container/pkgs/container/anybodycon-linux-minimal
LABEL org.opencontainers.image.title "anybodycon-linux-minimal"
LABEL org.opencontainers.image.description "Minimal image with AnyBody in a linux docker container"
LABEL org.opencontainers.image.licenses "https://www.anybodytech.com/legal/software-license-agreement/"


COPY --from=anybody-build-store --link --chown=${MAMBA_USER} ["extra" ,  "/home/${MAMBA_USER}/.wine/drive_c/Program Files/AnyBody Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/"]

#USER root

# Remove _pth file to allow overwriting PYTHON environment variables etc. 
RUN rm /home/${MAMBA_USER}/.wine/drive_c/Program\ Files/AnyBody\ Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/Python/python37._pth 

ARG AMS_MKL_DIR=/home/${MAMBA_USER}/.wine/drive_c/Program\ Files/AnyBody\ Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/AnyBody.MKL-2019.1.144-x64
ARG AMS_PYTHON_MKL_DIR=/home/${MAMBA_USER}/.wine/drive_c/Program\ Files/AnyBody\ Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/Python/Library/bin


USER root

# The following files are excluded in .dockeringore and we link to 
# the AnyBody copies to save image size.
RUN ln "${AMS_MKL_DIR}/mkl_avx2.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_avx2.dll" \
   && ln "${AMS_MKL_DIR}/mkl_avx512.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_avx512.dll" \
   && ln "${AMS_MKL_DIR}/mkl_core.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_core.dll" \
   && ln "${AMS_MKL_DIR}/mkl_intel_thread.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_intel_thread.dll"


USER $MAMBA_USER


RUN micromamba install --yes --name base --channel conda-forge --channel bioconda --channel anybody \
      nomkl  \
      snakemake-minimal \
      pandas  \
      pytest  \
      pytest-xdist  \
      anypytools \
      pytest-h5compare && \
    micromamba clean --all --yes



ENV PYTHONHASHSEED=1234

ENV WINEPATH=C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Library\\mingw-w64\\bin;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Library\\usr\\bin;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Library\\bin;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Scripts;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\bin;c:\\windows\\system32;c:\\windows;c:\\windows\\system32\\wbem
ENV SystemRoot=c:\\windows
ENV SystemDrive=c:

# WORKDIR $HOME


