#syntax=docker/dockerfile:1.4

ARG ANYBODY_VERSION 7.4
ARG ANYBODY_VERSION_PATCH 2
ARG ANYBODY_VERSION_SUFFIX ""
ARG BUILD_NUMBER 0

ARG BASE_IMAGE="ghcr.io/anybody/anybodycon-linux-minimal"
ARG TAG=${ANYBODY_VERSION}.${ANYBODY_VERSION_PATCH}${ANYBODY_VERSION_SUFFIX}-${BUILD_NUMBER}

FROM ghcr.io/anybody/container-build-store:${ANYBODY_VERSION}.${ANYBODY_VERSION_PATCH}${ANYBODY_VERSION_SUFFIX} as anybody-build-store


FROM ${BASE_IMAGE}:${TAG}
ARG ANYBODY_VERSION
ARG ANYBODY_VERSION_SUFFIX

LABEL org.opencontainers.image.url https://github.com/AnyBody/anybody-container/pkgs/container/anybodycon-linux-minimal
LABEL org.opencontainers.image.title "anybodycon-linux-minimal"
LABEL org.opencontainers.image.description "Minimal image with AnyBody in a linux docker container"
LABEL org.opencontainers.image.licenses "https://www.anybodytech.com/legal/software-license-agreement/"


COPY --from=anybody-build-store --link --chown=${MAMBA_USER} ["extra" ,  "/wine/drive_c/Program Files/AnyBody Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/"]

#USER root

# Remove _pth file to allow overwriting PYTHON environment variables etc. 
RUN rm /wine/drive_c/Program\ Files/AnyBody\ Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/Python/python37._pth 

ARG AMS_MKL_DIR=/wine/drive_c/Program\ Files/AnyBody\ Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/AnyBody.MKL-2019.1.144-x64
ARG AMS_PYTHON_MKL_DIR=/wine/drive_c/Program\ Files/AnyBody\ Technology/AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}/Python/Library/bin


USER root

# The following files are excluded in .dockeringore and we link to 
# the AnyBody copies to save image size.
RUN ln "${AMS_MKL_DIR}/mkl_avx2.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_avx2.dll" \
   && ln "${AMS_MKL_DIR}/mkl_avx512.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_avx512.dll" \
   && ln "${AMS_MKL_DIR}/mkl_core.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_core.dll" \
   && ln "${AMS_MKL_DIR}/mkl_intel_thread.dll"  "${AMS_PYTHON_MKL_DIR}/mkl_intel_thread.dll"


USER $MAMBA_USER


RUN micromamba install --yes --name base --channel conda-forge --channel bioconda --channel anybody \
      nomkl  \
      snakemake-minimal \
      pandas  \
      pytest  \
      pytest-xdist  \
      anypytools \
      git \
      pytest-h5compare && \
    micromamba clean --all --yes

RUN cd /opt/conda && \
  find -name '*.a' -delete && \
  rm -rf ./include && \
  rm ./lib/libpython3.10.so.1.0 && \
  find -name '__pycache__' -type d -exec rm -rf '{}' '+' && \
  rm -rf  ./lib/python3.10/idlelib ./lib/python3.10/ensurepip \
    ./lib/libasan.so.5.0.0 \
    ./lib/libtsan.so.0.0.0 \
    ./lib/liblsan.so.0.0.0 \
    ./lib/libubsan.so.1.0.0 \
    ./bin/x86_64-conda-linux-gnu-ld \
    ./bin/sqlite* \
    ./share/terminfo && \
  find ./lib/python3.10/site-packages/scipy -name 'tests' -type d -exec rm -rf '{}' '+' && \
  find ./lib/python3.10/site-packages/numpy -name 'tests' -type d -exec rm -rf '{}' '+' && \
  find ./lib/python3.10/site-packages/pandas -name 'tests' -type d -exec rm -rf '{}' '+' && \
  find ./lib/python3.10/site-packages -name '*.pyx' -delete && \
  rm -rf ./lib/python3.10/site-packages/uvloop/loop.c


ENV PYTHONHASHSEED=1234

ENV WINEPATH=C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Library\\mingw-w64\\bin;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Library\\usr\\bin;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Library\\bin;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\Scripts;C:\\Program\ Files\\AnyBody\ Technology\\AnyBody.${ANYBODY_VERSION}${ANYBODY_VERSION_SUFFIX}\\Python\\bin;c:\\windows\\system32;c:\\windows;c:\\windows\\system32\\wbem
ENV SystemRoot=c:\\windows
ENV SystemDrive=c:

ENV PATH "$MAMBA_ROOT_PREFIX/bin:$PATH"

# WORKDIR $HOME


