name: Build and push AnyBodyCon linux images

on:
  push:
    branches: ['release']
  pull_request:
    branches:
      - 'main'


jobs:
  create-images:
    name: Linux images for AnyBody.${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - anybody_version: 7.4
            anybody_version_patch: 4
            anybody_version_suffix: ""
            build_number: 3
          - anybody_version: 7.5
            anybody_version_patch: 0
            anybody_version_suffix: "_Beta"
            build_number: 5

            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push AnyBodyCon Slim image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-anybodycon-slim
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ANYBODY_VERSION=${{ matrix.anybody_version }}
            ANYBODY_VERSION_PATCH=${{ matrix.anybody_version_patch }}
            ANYBODY_VERSION_SUFFIX=${{ matrix.anybody_version_suffix }}
          tags: |
              ghcr.io/anybody/anybodycon-slim:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}-${{ matrix.build_number }}
              ghcr.io/anybody/anybodycon-slim:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-slim:${{ matrix.anybody_version }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-slim:latest${{ matrix.anybody_version_suffix }}

      - name: Build and push AnyBodyCon slim conda image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-anybodycon-slim-micromamba
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          build-args: |
            ANYBODY_VERSION=${{ matrix.anybody_version }}
            ANYBODY_VERSION_PATCH=${{ matrix.anybody_version_patch }}
            ANYBODY_VERSION_SUFFIX=${{ matrix.anybody_version_suffix }}
            BUILD_NUMBER=${{ matrix.build_number }}
          tags: |
              ghcr.io/anybody/anybodycon-slim-micromamba:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}-${{ matrix.build_number }}
              ghcr.io/anybody/anybodycon-slim-micromamba:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-slim-micromamba:${{ matrix.anybody_version }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-slim-micromamba:latest${{ matrix.anybody_version_suffix }}



      - name: Build and push AnyBodyCon full image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-anybodycon
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ANYBODY_VERSION=${{ matrix.anybody_version }}
            ANYBODY_VERSION_PATCH=${{ matrix.anybody_version_patch }}
            ANYBODY_VERSION_SUFFIX=${{ matrix.anybody_version_suffix }}
            BUILD_NUMBER=${{ matrix.build_number }}
          tags: |
              ghcr.io/anybody/anybodycon:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}-${{ matrix.build_number }}
              ghcr.io/anybody/anybodycon:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon:${{ matrix.anybody_version }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon:latest${{ matrix.anybody_version_suffix }}


      - name: Build and push AnyBodyCon full conda image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-anybodycon-micromamba
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ANYBODY_VERSION=${{ matrix.anybody_version }}
            ANYBODY_VERSION_PATCH=${{ matrix.anybody_version_patch }}
            ANYBODY_VERSION_SUFFIX=${{ matrix.anybody_version_suffix }}
            BUILD_NUMBER=${{ matrix.build_number }}
          tags: |
              ghcr.io/anybody/anybodycon-micromamba:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}-${{ matrix.build_number }}
              ghcr.io/anybody/anybodycon-micromamba:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-micromamba:${{ matrix.anybody_version }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-micromamba:latest${{ matrix.anybody_version_suffix }}

      - name: Build and push AnyBodyCon GitHub actions image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-anybodycon-github-actions
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          build-args: |
            ANYBODY_VERSION=${{ matrix.anybody_version }}
            ANYBODY_VERSION_PATCH=${{ matrix.anybody_version_patch }}
            ANYBODY_VERSION_SUFFIX=${{ matrix.anybody_version_suffix }}
            BUILD_NUMBER=${{ matrix.build_number }}
          tags: |
              ghcr.io/anybody/anybodycon-github-actions:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}-${{ matrix.build_number }}
              ghcr.io/anybody/anybodycon-github-actions:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-github-actions:${{ matrix.anybody_version }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-github-actions:latest${{ matrix.anybody_version_suffix }}



      - name: Build and push AnyBodyCon slim devcontainer image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-anybodycon-slim
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ANYBODY_VERSION=${{ matrix.anybody_version }}
            ANYBODY_VERSION_PATCH=${{ matrix.anybody_version_patch }}
            ANYBODY_VERSION_SUFFIX=${{ matrix.anybody_version_suffix }}
            BASE_IMAGE=mcr.microsoft.com/devcontainers/universal
            DISTRO=ubuntu
            DISTRO_VERSION=focal
            ANYBODY_USER=codespace
            TAG=2.3.1-focal
          tags: |
              ghcr.io/anybody/anybodycon-slim-devcontainer:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}-${{ matrix.build_number }}
              ghcr.io/anybody/anybodycon-slim-devcontainer:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-slim-devcontainer:${{ matrix.anybody_version }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-slim-devcontainer:latest${{ matrix.anybody_version_suffix }}


      - name: Build and push AnyBodyCon devcontainer image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-anybodycon
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          build-args: |
            ANYBODY_VERSION=${{ matrix.anybody_version }}
            ANYBODY_VERSION_PATCH=${{ matrix.anybody_version_patch }}
            ANYBODY_VERSION_SUFFIX=${{ matrix.anybody_version_suffix }}
            BUILD_NUMBER=${{ matrix.build_number }}
            BASE_IMAGE=ghcr.io/anybody/anybodycon-slim-devcontainer
            ANYBODY_USER=codespace
          tags: |
              ghcr.io/anybody/anybodycon-devcontainer:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}-${{ matrix.build_number }}
              ghcr.io/anybody/anybodycon-devcontainer:${{ matrix.anybody_version }}.${{ matrix.anybody_version_patch }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-devcontainer:${{ matrix.anybody_version }}${{ matrix.anybody_version_suffix }}
              ghcr.io/anybody/anybodycon-devcontainer:latest${{ matrix.anybody_version_suffix }}


